### ISSUE TITLE
Measures URL out of date

### ISSUE THREAD

**Issue by rtobar** [casacore/homebrew-tap#6]
Hi,

The URL for the measures data is out of date, so the formula is currently unusable. Could that be updated? Thanks!

**Comment by rtobar** [comment]
Thanks a lot @tammojan! I've asked @james-strauss-uwa to double-check on our end that the new URL is working correctly

**Comment by james-strauss-uwa** [comment]
Yes it is. Thanks both!

**Comment by tammojan** [comment]
Great, thanks for testing.
